cms_patterns = [
    ("WordPress", "/wp-content/"),
    ("Joomla", "/images/joomla.png"),
    ("Drupal", "/modules/system/"),
    ("Magento", "/skin/frontend/"),
    ("Shopify", "/cdn.shopify.com/"),
    ("PrestaShop", "/themes/default-bootstrap/"),
    ("OpenCart", "/catalog/view/theme/default/"),
    ("Ghost", "Ghost is a publishing platform"),
    ("Ghost", '<meta name="generator" content="Ghost'),
    ("Magento2", "/pub/static/frontend/"),
    ("Wix", "static.parastorage.com/"),
    ("Squarespace", "static1.squarespace.com/"),
    ("TYPO3", "This website is powered by TYPO3."),
    ("Blogger", "blogger.com/static/v1/widgets/"),
    ("Adobe Experience Manager", "/libs/granite/"),
    ("Drupal 8", "/core/assets/vendor/"),
    ("MediaWiki", "/mediawiki/"),
    ("Discuz!", "content/plugins"),
    ("Invision Community", "ipsType_"),
    ("Liferay", "/html/js/aui/"),
    ("Umbraco", "/umbraco/"),
    ("DotNetNuke", "dnn"),
    ("Concrete5", "/application/js/ckeditor"),
    ("Moodle", "/theme/image.php?theme="),
    ("XOOPS", "XOOPS - Web Application Platform"),
    ("Zen Cart", "templates/templates_default/"),
    ("phpBB", "phpBB Group"),
    ("vBulletin", '<meta name="generator" content="vBulletin'),
    ("osCommerce", '<meta name="generator" content="osCommerce'),
    ("Dotclear", "/dotclear/"),
    ("SPIP", '<meta name="generator" content="SPIP'),
    ("b2evolution", "/skins/kubrick/"),
    ("Textpattern", "/textpattern/"),
    ("Serendipity", "/templates/default/css/"),
    ("CMS Made Simple", '<meta name="generator" content="CMS Made Simple'),
    ("Movable Type", "/mt-static/"),
    ("Fork CMS", "/src/Frontend/"),
    ("SilverStripe", "/themes/silverstripe/templates/"),
    ("ThinkPHP", "thinkphp"),
    ("ecshop", "ECSHOP"),
    ("discuz", "Discuz!"),
    ("phpwind", "phpwind"),
    ("dedecms", "DedeCMS"),
    ("finecms", "finecms"),
    ("oneapm", "OneAPM"),
    ("phpcms", "phpcms"),
    ("opencart", "Powered By OpenCart"),
    ("z-blog", "Z-BlogPHP"),
    ("Typecho", '<meta name="generator" content="Typecho'),
    ("Hexo", 'hexo-generator'),
    ("Django", 'csrfmiddlewaretoken'),
    ("Flask", '<title>Welcome to Flask</title>'),
    ("Tornado", 'Tornado Web Server'),
    ("Gitea", '<title>Gitea: Git with a cup of tea</title>'),
    ("Gogs", '<title>Gogs: Go Git Service</title>'),
    ("Z-BlogPHP", "Z-BlogPHP"),
    ("Typecho", '<meta name="generator" content="Typecho'),
    ("Hexo", 'hexo-generator'),
    ("Discuz!", "content/plugins"),
    ("ECShop", "ECSHOP"),
    ("phpwind", "phpwind"),
    ("DedeCMS", "DedeCMS"),
    ("FineCMS", "FineCMS"),
    ("OneAPM", "OneAPM"),
    ("phpcms", "phpcms"),
    ("OpenCart", "Powered By OpenCart"),
    ("Z-Blog", "Z-BlogPHP"),
    ("OneThink", "OneThink"),
    ("MetInfo", "Powered by MetInfo"),
    ("ShopNC", "ShopNC"),
    ("Taobao商城", "淘宝商城"),
    ("JFinal", "JFinal"),
    ("Ecshop", "ecshop"),
    ("EMLOG", "Powered by Emlog"),
    ("PbootCMS", "PbootCMS"),
    ("Mao10CMS", "Mao10CMS"),
    ("Umbraco", "/umbraco/"),
    ("Subrion", "Subrion CMS"),
    ("WebPlus", "WebPlus"),
    ("Drupal 8", "/core/assets/vendor/"),
    ("MediaWiki", "/mediawiki/"),
    ("Invision Community", "ipsType_"),
    ("Liferay", "/html/js/aui/"),
    ("DotNetNuke", "dnn"),
    ("Concrete5", "/application/js/ckeditor"),
    ("Moodle", "/theme/image.php?theme="),
    ("Plone", '<meta name="generator" content="Plone'),
    ("XOOPS", "XOOPS - Web Application Platform"),
    ("Zen Cart", "templates/templates_default/"),
    ("phpBB", "phpBB Group"),
    ("vBulletin", '<meta name="generator" content="vBulletin'),
    ("osCommerce", '<meta name="generator" content="osCommerce'),
    ("Dotclear", "/dotclear/"),
    ("SPIP", '<meta name="generator" content="SPIP'),
    ("b2evolution", "/skins/kubrick/"),
    ("Textpattern", "/textpattern/"),
    ("Serendipity", "/templates/default/css/"),
    ("CMS Made Simple", '<meta name="generator" content="CMS Made Simple'),
    ("Movable Type", "/mt-static/"),
    ("Fork CMS", "/src/Frontend/"),
    ("SilverStripe", "/themes/silverstripe/templates/"),
    ("GitLab", 'GitLab Community Edition'),
]